/**
 * One-time Google authorization for the orchestrator from GitHub Actions, usable from a phone (pure helpers; I/O in
 * scripts/orchestrator/google-oauth-actions.ts). Design (official Google / GitHub docs, checked 2026-10-10):
 *  - the device flow does not allow the `drive` scope (only drive.file / drive.appdata, which cannot see files that
 *    ChatGPT's or Claude's connectors create); service accounts / Workload Identity Federation cannot act as a
 *    personal Gmail user; the OAuth Playground makes the owner copy the refresh token by hand. All ruled out.
 *  - "Desktop app" client with the loopback redirect. On the phone the browser lands on an unreachable
 *    http://127.0.0.1 page whose address carries a single-use code.
 *  - NOTHING travels through workflow inputs (they are visible in a public repository): the owner stores that
 *    address as the environment secret GOOGLE_OAUTH_REDIRECT (encrypted, masked in logs), and "finish" deletes it.
 *  - PKCE (RFC 7636) with a RANDOM verifier per attempt, generated by "start" and kept as the environment secret
 *    GOOGLE_OAUTH_PENDING with its state and creation time; "finish" accepts it once, within PENDING_TTL_MS, only
 *    if the returned state matches, and deletes it whatever happens (no replay, no reuse).
 *  - Every secret lives in the GitHub environment "orchestrator", restricted to the default branch: a workflow pushed
 *    on any other branch cannot read the refresh token, the client secret or the writer token.
 *  - The consent screen must be "In production" (unverified is fine for personal use): in "Testing" Google issues
 *    refresh tokens that expire after 7 days.
 */
import { createHash, randomBytes } from "node:crypto";

export const DRIVE_SCOPE = "https://www.googleapis.com/auth/drive";
export const LOOPBACK_REDIRECT = "http://127.0.0.1:8765/callback";
export const OAUTH_ENVIRONMENT = "orchestrator";
export const PENDING_TTL_MS = 15 * 60_000;
const STATE_RE = /^[0-9a-f]{32}$/;
const VERIFIER_RE = /^[A-Za-z0-9._~-]{43,128}$/;

export type Pending = { v: 1; state: string; verifier: string; createdAt: string };

/** A fresh attempt: random state (CSRF) and random PKCE verifier (64 base64url chars, 384 bits). */
export const newPending = (now = new Date()): Pending => ({ v: 1, state: randomBytes(16).toString("hex"), verifier: randomBytes(48).toString("base64url"), createdAt: now.toISOString() });

export const pkceChallenge = (verifier: string) => createHash("sha256").update(verifier).digest("base64url");

export function consentUrl(clientId: string, pending: Pick<Pending, "state" | "verifier">): string {
  if (!STATE_RE.test(pending.state) || !VERIFIER_RE.test(pending.verifier)) throw new Error("intento inválido");
  const u = new URL("https://accounts.google.com/o/oauth2/v2/auth");
  u.search = new URLSearchParams({
    client_id: clientId, redirect_uri: LOOPBACK_REDIRECT, response_type: "code", scope: DRIVE_SCOPE,
    access_type: "offline", prompt: "consent", state: pending.state, code_challenge: pkceChallenge(pending.verifier), code_challenge_method: "S256",
  }).toString();
  return u.toString();
}

/** The stored attempt: well formed, at most PENDING_TTL_MS old (never reused: "finish" deletes it). */
export function parsePending(raw: string | undefined, now = Date.now()): { ok: true; pending: Pending } | { ok: false; reason: string } {
  let p: Partial<Pending>;
  try { p = JSON.parse(raw ?? "") as Partial<Pending>; } catch { return { ok: false, reason: "no hay un intento pendiente: ejecuta primero «start»" }; }
  if (p.v !== 1 || !STATE_RE.test(p.state ?? "") || !VERIFIER_RE.test(p.verifier ?? "") || !Number.isFinite(Date.parse(p.createdAt ?? ""))) return { ok: false, reason: "el intento pendiente no es válido: ejecuta «start» otra vez" };
  const age = now - Date.parse(p.createdAt!);
  if (age < 0 || age > PENDING_TTL_MS) return { ok: false, reason: "el intento caducó (más de 15 minutos): ejecuta «start» otra vez" };
  return { ok: true, pending: p as Pending };
}

export type ParsedRedirect = { ok: true; code: string } | { ok: false; reason: string };

/** The address the browser landed on; its state must be the one of the pending attempt (CSRF / mix-up). */
export function parseRedirect(raw: string | undefined, expectedState: string): ParsedRedirect {
  let u: URL;
  try { u = new URL((raw ?? "").trim()); } catch { return { ok: false, reason: "el secreto GOOGLE_OAUTH_REDIRECT no contiene una URL" }; }
  if ((u.hostname !== "127.0.0.1" && u.hostname !== "localhost") || u.pathname !== "/callback") return { ok: false, reason: "la dirección no es la de retorno local (127.0.0.1:8765/callback)" };
  const err = u.searchParams.get("error");
  if (err) return { ok: false, reason: `Google devolvió «${err.slice(0, 40)}» (¿se canceló el consentimiento?)` };
  if (u.searchParams.get("state") !== expectedState) return { ok: false, reason: "la dirección no corresponde al último «start» (estado distinto)" };
  const code = u.searchParams.get("code") ?? "";
  if (!/^[A-Za-z0-9/_.-]{10,512}$/.test(code)) return { ok: false, reason: "falta el código de autorización o no es válido" };
  return { ok: true, code };
}

export function tokenRequestBody(input: { code: string; verifier: string; clientId: string; clientSecret: string }): string {
  return new URLSearchParams({
    code: input.code, client_id: input.clientId, client_secret: input.clientSecret, redirect_uri: LOOPBACK_REDIRECT,
    grant_type: "authorization_code", code_verifier: input.verifier,
  }).toString();
}

export type TokenCheck = { ok: true; refreshToken: string } | { ok: false; reason: string };

/** The exchange must return a refresh token with the full drive scope. */
export function checkTokenResponse(status: number, body: { refresh_token?: string; scope?: string; error?: string } | null): TokenCheck {
  if (status !== 200 || !body) return { ok: false, reason: `Google rechazó el canje (${body?.error?.slice(0, 40) ?? status}); el código dura minutos y sirve una sola vez: repite «start»` };
  if (!body.refresh_token) return { ok: false, reason: "Google no entregó un token de renovación (repite «start»: el consentimiento pide acceso sin conexión)" };
  if (!(body.scope ?? "").split(" ").includes(DRIVE_SCOPE)) return { ok: false, reason: "el permiso concedido no incluye Google Drive completo (marca la casilla de Drive en el consentimiento)" };
  return { ok: true, refreshToken: body.refresh_token };
}
