/** One authorized phrase audition, official API, ledger first, private encrypted delivery. */
import {mkdtemp,writeFile,readFile,mkdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash,randomBytes,createCipheriv} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {createServiceClient} from '../../src/lib/supabase/service';import {supabaseLedgerStore} from '../../src/lib/paid-calls/supabase-ledger-store';import {supabaseResultStore} from '../../src/lib/paid-calls/result-store';import {gatedVoiceConversion} from '../../src/lib/paid-calls/gated-voice-conversion';import {acquireCapacityHolds,supabaseCapacityHoldStore,type AcquiredHold} from '../../src/lib/paid-calls/capacity-hold';import {ProviderRejectedError} from '../../src/lib/paid-calls/errors';
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');const exec=promisify(execFile);
async function main(){
 const sb=createServiceClient(),ledger=supabaseLedgerStore(sb),results=supabaseResultStore(sb),capacity=supabaseCapacityHoldStore(sb);
 const auth=await ledger.get('vfx_closing_voice_authorization_v1'),plan=await ledger.get('vfx_closing_voice_audition_plan_v1');if(auth?.status!=='COMMITTED'||auth.method!=='human_direction'||!auth.resultRef||plan?.status!=='COMMITTED'||!plan.resultRef)throw new Error('VFX_VOICE_PLAN_NOT_AUTHORIZED');const c={...JSON.parse(auth.resultRef),...JSON.parse(plan.resultRef)};
 if(c.approved!==true||c.paidCallAuthorized!==true||c.maximumAuditions!==1||c.maximumSeconds>10||c.maximumUsd>.02||c.usdPerMinute!==.12)throw new Error('VFX_VOICE_SCOPE_CHANGED');
 const owner=await sb.from('vfx_director_jobs').select('owner_id').eq('id','precampaign-three-worlds-v1-preparation').maybeSingle();const u=await sb.auth.admin.getUserById(c.ownerId);if(owner.error||owner.data?.owner_id!==c.ownerId||u.error||!u.data.user?.email_confirmed_at)throw new Error('VFX_OWNER_UNVERIFIED');
 const apiKey=process.env.ELEVENLABS_API_KEY;if(!apiKey)throw new Error('VFX_VOICE_KEY_MISSING');
 const root=await mkdtemp(join(tmpdir(),'voice-audition-'));let holds:AcquiredHold[]=[];
 try{
  const source=await results.getBytes(c.sourcePath);if(!source||hash(source)!==c.sourceSha256)throw new Error('VFX_VOICE_SOURCE_CHANGED');await writeFile(join(root,'original.mp4'),source);await writeFile(join(root,'config.json'),JSON.stringify(c));
  // Select an exact integer count of resampled audio samples; codec seek rounding must not extend the authorized phrase.
  await exec('ffmpeg',['-v','error','-y','-i',join(root,'original.mp4'),'-vn','-ac','1','-ar','44100','-af','aresample=44100,atrim=start_sample='+Math.round(c.phraseStart*44100)+':end_sample='+Math.round(c.phraseEnd*44100)+',asetpts=PTS-STARTPTS','-c:a','pcm_s16le',join(root,'phrase.wav')]);const audio=await readFile(join(root,'phrase.wav'));
  const probe=JSON.parse((await exec('ffprobe',['-v','error','-show_format','-of','json',join(root,'phrase.wav')])).stdout);const exactSeconds=Number(probe.format.duration);if(Math.abs(exactSeconds-(c.phraseEnd-c.phraseStart))>.025)throw new Error('VFX_VOICE_PHRASE_DURATION_CHANGED');
  const guarded=await gatedVoiceConversion({ledger,results,apiKey,beforePost:async()=>{
   const get=async(path:string)=>{const r=await fetch('https://api.elevenlabs.io/v1/'+path,{headers:{'xi-api-key':apiKey},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new ProviderRejectedError('VFX_PREFLIGHT_HTTP_'+r.status,'rejected_final');return r.json();};
   const [sub,voice,models]=await Promise.all([get('user/subscription'),get('voices/'+encodeURIComponent(c.voiceId)),get('models')]);const model=models.find((m:{model_id:string})=>m.model_id===c.modelId);
   if(sub.status!=='active'||sub.tier==='free'||voice.fine_tuning?.state?.[c.modelId]!=='fine_tuned'||!model?.can_do_voice_conversion||model.model_rates?.character_cost_multiplier!==1||voice.sharing?.rate!==1||!model.languages.some((l:{language_id:string})=>l.language_id==='es'))throw new ProviderRejectedError('VFX_VOICE_OR_RATE_UNVERIFIED','rejected_final');
   const checkedAt=new Date().toISOString(),available=Number(sub.character_limit)-Number(sub.character_count);if(!Number.isFinite(available))throw new ProviderRejectedError('VFX_VOICE_BALANCE_UNKNOWN','rejected_final');
   const acquired=await acquireCapacityHolds({store:capacity,balance:{read:async()=>({known:true,provider:'elevenlabs',available,unit:'character',checkedAt})}},{requestId:c.projectId,demands:[{provider:'elevenlabs',units:Math.ceil(exactSeconds*1000/60),usd:exactSeconds*.12/60}]});if(!acquired.acquired)throw new ProviderRejectedError('VFX_VOICE_CAPACITY_UNAVAILABLE','rejected_final');holds=acquired.holds;
  }},{projectId:c.projectId,shotId:'closing-cta-voice-audition-v1',voiceId:c.voiceId,modelId:c.modelId,audio,seconds:exactSeconds,maximumSeconds:c.maximumSeconds,maximumUsd:c.maximumUsd,usdPerMinute:c.usdPerMinute,voiceSettings:c.voiceSettings,seed:29});
  for(const h of holds){if(!await capacity.settleHold(h.key,'COMMITTED'))throw new Error('VFX_VOICE_HOLD_SETTLEMENT_REQUIRED');}
  await writeFile(join(root,'converted.mp3'),guarded.result.audio);await writeFile(join(root,'conversion-receipt.json'),JSON.stringify({key:guarded.key,reused:guarded.reused,costUsd:guarded.costUsd,...guarded.result.meta}));
  const stageReport=await results.getJson<{sha256:string;trim:number[]}> (c.projectId+'/closing-launch-stage/closing-report.json');if(stageReport){const video=await results.getBytes(c.projectId+'/closing-launch-stage/'+stageReport.sha256+'.mp4');if(video&&hash(video)===stageReport.sha256){await writeFile(join(root,'stage.mp4'),video);await writeFile(join(root,'stage-report.json'),JSON.stringify(stageReport));}}
  try{await exec('python3',['scripts/vfx/closing-voice-audition.py',root],{timeout:10*60_000,maxBuffer:1024*1024});}catch(e){const err=e as Error&{stderr?:string};await ledger.insert({idempotencyKey:'vfx_closing_voice_render_failure_'+process.env.GITHUB_RUN_ID,projectId:c.projectId,shotId:'closing-voice-render',provider:'internal',model:'diagnostic/1',method:'private_diagnostic',attemptKind:'review',reservedUsd:0,committedUsd:0,status:'COMMITTED',providerJobId:null,resultRef:JSON.stringify({message:err.message,stderr:err.stderr,key:guarded.key,retryPaidCall:false}),updatedAt:new Date().toISOString()});throw new Error('VFX_VOICE_RENDER_FAILED_PAID_AUDIO_RETAINED');}
  const report=JSON.parse(await readFile(join(root,'voice-report.json'),'utf8'));await results.putJson(c.projectId+'/closing-voice/voice-report.json',report);
  const plain=await readFile(join(root,'voice-review.zip')),key=randomBytes(32),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([iv,cipher.update(plain),cipher.final(),cipher.getAuthTag()]);const deliveryKey='vfx_closing_voice_delivery_'+process.env.GITHUB_RUN_ID+'_'+process.env.GITHUB_RUN_ATTEMPT;
  if(!await ledger.insert({idempotencyKey:deliveryKey,projectId:c.projectId,shotId:'closing-voice-delivery',provider:'internal',model:'encrypted-review/1',method:'encrypted_delivery',attemptKind:'review',reservedUsd:0,committedUsd:0,status:'COMMITTED',providerJobId:null,resultRef:JSON.stringify({ownerId:c.ownerId,keyBase64:key.toString('base64'),plainSha256:hash(plain),encryptedSha256:hash(encrypted),report}),updatedAt:new Date().toISOString()}))throw new Error('VFX_DELIVERY_EXISTS');
  await mkdir('vfx-closing-voice-encrypted',{recursive:true});await writeFile('vfx-closing-voice-encrypted/voice-review.enc',encrypted);await writeFile('vfx-closing-voice-encrypted/delivery.json',JSON.stringify({deliveryKey,plaintextMediaExported:false}));console.log(JSON.stringify({auditionRendered:true,reused:guarded.reused,paidPosts:guarded.reused?0:1,reviewApproved:false}));
 }finally{await rm(root,{recursive:true,force:true});}
}
main().catch(e=>{console.error(e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'VFX_VOICE_AUDITION_BLOCKED');process.exitCode=1;});
