/** Private, zero-cost replay capsule. No provider credentials or generation calls. */
import {createHash,randomBytes,createCipheriv} from 'node:crypto';
import {mkdtemp,writeFile,readFile,mkdir,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {createServiceClient} from '../../src/lib/supabase/service';import {supabaseLedgerStore} from '../../src/lib/paid-calls/supabase-ledger-store';import {supabaseResultStore} from '../../src/lib/paid-calls/result-store';
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
async function main(){const sb=createServiceClient(),ledger=supabaseLedgerStore(sb),results=supabaseResultStore(sb);const row=await ledger.get('vfx_master_asset_recovery_v1');if(row?.status!=='COMMITTED'||row.method!=='human_direction'||!row.resultRef)throw new Error('RECOVERY_NOT_AUTHORIZED');const cfg=JSON.parse(row.resultRef);if(cfg.approved!==true||cfg.maximumAdditionalUsd!==0||cfg.deploymentAuthorized!==false)throw new Error('RECOVERY_SCOPE_INVALID');const u=await sb.auth.admin.getUserById(cfg.ownerId);if(u.error||!u.data.user?.email_confirmed_at)throw new Error('OWNER_UNVERIFIED');const job=await sb.from('vfx_director_jobs').select('owner_id').eq('id','precampaign-three-worlds-v1-preparation').maybeSingle();if(job.data?.owner_id!==cfg.ownerId)throw new Error('OWNER_MISMATCH');const root=await mkdtemp(join(tmpdir(),'master-replay-'));try{const manifest:any={assets:[],paid:[],providerCalls:0};for(const a of cfg.assets){if(!/^[a-z0-9.-]+$/.test(a.name))throw new Error('NAME_INVALID');const r=await sb.storage.from(a.bucket).download(a.path);if(r.error||!r.data)throw new Error('ASSET_MISSING');const b=Buffer.from(await r.data.arrayBuffer());await writeFile(join(root,a.name),b);manifest.assets.push({...a,sha256:sha(b)});}
for(const key of cfg.paidMetadataKeys){const r=await ledger.get(key);if(r?.status!=='COMMITTED'||!r.resultRef)throw new Error('PAID_REPLAY_NOT_COMMITTED');const m:any=await results.getJson(r.resultRef);const p=m?.audioPath||m?.videoPath;if(!p||!m.sha256)throw new Error('PAID_METADATA_INVALID');const b=await results.getBytes(p);if(!b||sha(b)!==m.sha256)throw new Error('PAID_REPLAY_HASH_MISMATCH');const name=key+(m.videoPath?'.mp4':'.mp3');await writeFile(join(root,name),b);manifest.paid.push({key,name,metadata:m});}
await writeFile(join(root,'manifest.json'),JSON.stringify(manifest));await promisify(execFile)('python3',['-c','import os,sys,zipfile\np=sys.argv[1]\nwith zipfile.ZipFile(p+".zip","w",zipfile.ZIP_STORED) as z:\n for f in os.listdir(p): z.write(os.path.join(p,f),f)',root]);const plain=await readFile(root+'.zip'),key=randomBytes(32),iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([iv,c.update(plain),c.final(),c.getAuthTag()]);const deliveryKey='vfx_master_recovery_'+process.env.GITHUB_RUN_ID+'_'+process.env.GITHUB_RUN_ATTEMPT;const receipt={ownerId:cfg.ownerId,keyBase64:key.toString('base64'),plainSha256:sha(plain),encryptedSha256:sha(encrypted),manifest};if(!await ledger.insert({idempotencyKey:deliveryKey,projectId:cfg.projectId,shotId:'master-assets',provider:'internal',model:'encrypted-replay/1',method:'encrypted_delivery',attemptKind:'review',reservedUsd:0,committedUsd:0,status:'COMMITTED',providerJobId:null,resultRef:JSON.stringify(receipt),updatedAt:new Date().toISOString()}))throw new Error('DELIVERY_EXISTS');await mkdir('master-recovery-encrypted',{recursive:true});for(let i=0;i<encrypted.length;i+=20*1024*1024)await writeFile('master-recovery-encrypted/part-'+String(i/(20*1024*1024)).padStart(3,'0')+'.enc',encrypted.subarray(i,i+20*1024*1024));console.log('PRIVATE_REPLAY_READY; PROVIDER_CALLS=0');await rm(root+'.zip',{force:true});}finally{await rm(root,{recursive:true,force:true});}}
main().catch(()=>{console.error('PRIVATE_REPLAY_BLOCKED');process.exitCode=1;});
